### ISSUE TITLE
T31 - Revisão e criação de tópicos do doc de arq

### ISSUE THREAD

**Issue by andrebargas** [fga-eps-mds/2019.1-PretEvent#100]
**Descrição**:  
Criar todos os tópicos faltante no doc de arquitetura, juntamente com a ilustração de diagramas

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Preencher tópicos vazios
- [x] Subir diagramas faltantes

**Comment by gustavocarvalho1002** [comment]
Atividade realizada. A revisão foi feita e documento encontra na pasta doc para vizualização.
