### ISSUE TITLE
T33 - Revisão da documentação do Projeto

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2019.1-PretEvent#103]
**Descrição**:  
Revisar Ortografia, formatação e versões dos documentos

**Documentos a serem Revisados**: 
- [x] TAP
- [x] EAP
- [x] Backlog
- [x] Canvas
- [x] Roadmap de Produto
- [x] Documento de Visão

**Comment by IanPSRocha** [comment]
Iniciarei a Revisão a começar pelo TAP

**Comment by IanPSRocha** [comment]
Ultimo documento, que era o de visão, está revisado e foi adicionado imagens referentes a referência visual e alternativas

**Comment by murilo-dan** [comment]
Adicionando tópicos complementares no Documento de Visão e melhorando formatação.
