### ISSUE TITLE
T35 - Swarm com monitoramento

### ISSUE THREAD

**Issue by Rdadamos** [fga-eps-mds/2019.1-PretEvent#108]
**Descrição**:  
Criar um cluster com o Docker Swarm com aplicações de monitoramento (Prometheus + Grafana)

**Atividades a serem realizadas**: 
- [x] Criar novas instâncias EC2
- [x] Configurar essas novas instâncias
- [x] Instalar rexray
- [x] Configurar nginx para produção
- [x] Adicionar aplicações de monitoramento do cluster no docker-compose-prod.yml
- [x] Configurar Prometheus
- [x] Configurar Grafana

**Comment by Rdadamos** [comment]
Começando

**Comment by Rdadamos** [comment]
Vamos ter 3 instâncias no nosso swarm

**Comment by Rdadamos** [comment]
Vamos instalar o rexray do docker nos nós do swarm para ter volumes montados em diferentes nós, integrando o docker com a AWS. Com esse driver, um volume criado vira um Elastic Block System (EBS) na AWS e é montado automaticamente nos nós do cluster.

**Comment by Rdadamos** [comment]
Para a R1 não funcionou. Voltando a mexer  para terminar para a R2

**Comment by gustavocarvalho1002** [comment]
Pr foi aceito! Deste modo, estou fechado a issue! 
Foi anexado no PR uma prova da funcionalidade do trabalho feito aqui!
