### ISSUE TITLE
F18 - Login de usuário no front

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#118]
**Descrição:**
Deverá ser desenvolvido no front uma modal onde usuário colocara seus dados e realizará o login. 

**Critério de aceitação:**
- [x] Modal com os campo de login
- [x] Receber o token da API

**Comment by b2198** [comment]
Foi feito o pareamento com o @djorkaeffalexandre e @gustavocarvalho1002 para criação dos formulários de login

**Comment by b2198** [comment]
![Captura de tela de 2019-04-30 19-50-45](https://user-images.githubusercontent.com/26636105/56998338-54d96f80-6b81-11e9-92c0-311471bc86a6.png)

**Comment by b2198** [comment]
![Captura de tela de 2019-04-30 19-52-35](https://user-images.githubusercontent.com/26636105/56998407-8d794900-6b81-11e9-8a2f-fd16edd1c28a.png)

**Comment by gustavocarvalho1002** [comment]
Tarefa feita e merjada na devel. Prints acima evidenciam sua conclusão.
