### ISSUE TITLE
T37 - Adicionar campo de recompensa ao evento

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#119]
**Descrição**:  
Adicionar um campo para identificador de recompensa ao evento.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Criar migração que adiciona campo de id de recompensa ao evento.

**Comment by IanPSRocha** [comment]
Campo de id de recompensa adicionado na model
