### ISSUE TITLE
T38 - Linkar recompensa com evento no cliente

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#122]
**Descrição**:  
Adicionar recompensa a um evento no front-end.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Conferir se a recompensa existe.
- [x] Listar as recompensas existentes.

**Comment by murilo-dan** [comment]
Pareando com @Fealps para iniciar o desenvolvimento da feature.

**Comment by Fealps** [comment]
Finalizando Issue

**Comment by murilo-dan** [comment]
Retornando JSON mostrando o campo reward_id do evento criado com o id da recompensa escolhida.

![Captura de tela de 2019-05-01 21-55-15](https://user-images.githubusercontent.com/48605413/57052153-e87f6e80-6c5b-11e9-8fbf-01a19b058c1f.png)

**Comment by Fealps** [comment]
Aguardando Review no PR #125
