### ISSUE TITLE
T39 - Consertar vulnerabilidades

### ISSUE THREAD

**Issue by Rdadamos** [fga-eps-mds/2019.1-PretEvent#127]
**Descrição**:  
Arrumar as vulnerabilidades apontadas pelo GitHub

**Atividade(s) a ser(em) realizada(s)**: 
- [ ] Consertar vulnerabilidades

**Comment by Rdadamos** [comment]
As vulnerabilidades são no package-lock.json, é necessário rodar "npm audit fix" depois de "npm install"

**Comment by gustavocarvalho1002** [comment]
@Rdadamos , qual o status desta tarefa?

**Comment by gustavocarvalho1002** [comment]
Vulnerabilidades apontadas foram todas sanadas. Uma delas era sobre a versão do bootstrap, e a outra a versão do tar.
