### ISSUE TITLE
T36 - Criar serviço de redirecionamento e de alert para sucesso e erros.

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#131]
**Descrição**:  
Criar um serviço que permita mostrar alerts de sucesso e de erro para as operações realizadas no site e implementar um router para redirecionamento de telas nas operações.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Criar serviço de alert.
- [x] Criar serviço de redirecionamento.

**Comment by gustavocarvalho1002** [comment]
![Captura de tela de 2019-05-13 17-27-20](https://user-images.githubusercontent.com/23438547/57651752-6d478200-75a4-11e9-98bd-7fc32ba53870.png)
Tarefa concluída, porém issue foi esquecida e não fechada. @djorkaeffalexandre atentar para atualizar as issues de acordo com a atividade realizada
