### ISSUE TITLE
T41 - Busca de evento por parâmetro

### ISSUE THREAD

**Issue by murilo-dan** [fga-eps-mds/2019.1-PretEvent#137]
**Descrição**:  
Permite realizar busca de eventos no _backend_ utilizando parâmetros.

**Critério(s) de aceitação**: 
- [x] Permitir buscar eventos
- [x] Retornar evento por data e local

**Comment by murilo-dan** [comment]
Iniciando trabalho na _task_.

**Comment by murilo-dan** [comment]
_Task_ finalizada, PR aberto.
Aguardando _review_.

**Comment by gustavocarvalho1002** [comment]
Pr desta tarefa já foi aprovado! Fecharei esta issue!
