### ISSUE TITLE
T45 - Criar endpoint para listagem de player

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#141]
**Descrição**:  
Criar endpoint no back para retornar dados de player, mas só os campos de **nome**,**pontos** e **foto** devem ser retornados nesse link. 

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Disponibilizar endpoint para utilizar no front.

**Comment by murilo-dan** [comment]
Iniciando trabalho na _task_.

**Comment by murilo-dan** [comment]
Atualmente tentando retornar somente os campos desejados do banco de dados.

**Comment by murilo-dan** [comment]
Endpoint retornando os campos pedidos.

![Captura de tela de 2019-05-16 15-22-48](https://user-images.githubusercontent.com/48605413/57877604-a07d5180-77ee-11e9-8f53-131f941b5376.png)

**Comment by murilo-dan** [comment]
Observação: os objetos retornados já estão organizados de acordo com o campo **pontos** (maior valor no topo da lista).

**Comment by murilo-dan** [comment]
Pull Request feito, aguradando _review_.

**Comment by murilo-dan** [comment]
PR aceito, fechando a _issue_.
