### ISSUE TITLE
T46 - Revisar Documento de Visão

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2019.1-PretEvent#148]
**Descrição**:  
É necessário fazer uma revisão no documento de visão, pois o mesmo se encontra desatualizado em relação ao projeto no geral.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Revisão Ortográfica
- [x] Adicionar Gamificação
- [x] Revisar tópicos essenciais

**Comment by IanPSRocha** [comment]
Pareando com @Fealps para começar a Task

**Comment by IanPSRocha** [comment]
Eu e @Fealps revisamos os principais tópicos.

**Comment by Fealps** [comment]
Terminada a revisão e adicionando imagens faltantes.
