### ISSUE TITLE
T49 - Adcionar campo hora em evento

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#152]
**Descrição**:  
Colocar no registro de evento o campo hora. Deverá ser atualizado a página de vizualização de evento, o back-end e o formulário de cadastro de evento. 

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Atualizar o back-end com a adição do campo hora em evento.
- [x] Atualizar o formulário de registro de evento com o campo hora.
- [x] Atualizar a página de mostrar detalhes de evento para mostrar informação de hora.

**Comment by murilo-dan** [comment]
Iniciando tarefa.

**Comment by murilo-dan** [comment]
Devido a alguns problemas com o sistema operacional do meu computador, o desenvolvimento da tarefa acabou atrasando.
Tive que formatar o computador e fazer o setup completo das dependências necessárias.
Retornando ao desenvolvimento normal.

**Comment by murilo-dan** [comment]
Tarefa finalizada com a ajuda do @Rdadamos.

**Comment by murilo-dan** [comment]
PR aberto, aguardando review.
