### ISSUE TITLE
T50 - Fixar o footer

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#153]
**Descrição**:  
Fixar o footer no final da tela. 
Lembrando que na tela home ele não deve aparecer, mas isso já se encontra feito. 

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Verificar se em todas as telas o footer se encontra fixo no final

**Comment by Rdadamos** [comment]
Começando

**Comment by gustavocarvalho1002** [comment]
https://github.com/fga-eps-mds/2019.1-PretEvent/pull/163

PR ACEITO

**Comment by gustavocarvalho1002** [comment]
Favor finalizar tarefa!
