### ISSUE TITLE
T54 - Testes no Travis CI

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#158]
**Descrição**:  
Estudar como configurar a cobertura de testes no Travis CI

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Anexar links aqui(nesta issue).

**Comment by Rdadamos** [comment]
https://coverage.readthedocs.io/en/v4.5.x/

**Comment by Rdadamos** [comment]
https://docs.pytest.org

**Comment by Rdadamos** [comment]
https://docs.travis-ci.com/user/languages/python/

**Comment by Rdadamos** [comment]
https://coveralls-python.readthedocs.io

**Comment by Rdadamos** [comment]
Configurar a cobertura de testes no Code CLimate
https://docs.codeclimate.com/docs/configuring-test-coverage
