### ISSUE TITLE
T55 - Fazer exemplo de teste no Travis

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#159]
**Descrição**:  
Implementar um teste de exemplo integrado no travis.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Gerar evidência do teste aqui. 
- [x] Disponibilizar exemplo para MDS.

**Comment by Rdadamos** [comment]
Testes iniciais aqui:
https://github.com/fga-eps-mds/2019.1-PretEvent/blob/T55/service/mc1/players/tests.py

**Comment by Rdadamos** [comment]
Finalmente, testes rodando e relatórios sendo enviados para o Coveralls.

O maior problema foi combinar o .coverage gerado em cada container para enviar um relatório unificado ao Coveralls pelo Travis.

Utilizei o arquvio .coveragerc para configurar os caminhos para serem utilizados no combine conforme https://coverage.readthedocs.io/en/v4.5.x/config.html#paths

O truque é utilizar declarações de caminhos separadas por microsserviço: https://stackoverflow.com/questions/51852698/coverage-combine-results-from-different-containers

Como ficou no .travis.yml: https://github.com/fga-eps-mds/2019.1-PretEvent/blob/T55/.travis.yml#L30-L33

Relatórios por microsserviço exibidos no log do Travis:
![14](https://user-images.githubusercontent.com/17864231/59559226-0ff68480-8fd9-11e9-8f7b-fd85698a0b93.png)

Relatório unificado (o qual é enviado para o Coveralls) exibido no log do Travis:
![13](https://user-images.githubusercontent.com/17864231/59559131-80040b00-8fd7-11e9-9344-bde62a4a2215.jpeg)

Coveralls PretEvent: https://coveralls.io/github/fga-eps-mds/2019.1-PretEvent
