### ISSUE TITLE
T56 - Colocar um redirect ao fazer logout

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#160]
**Descrição**:  
Quando o usuário selecionar a opção sair na barra de navegação, á pagina deverá ser redirecionada para a /home e no local storage não deverá ter dados do token.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Colocar redirect no logout para a /home

**Comment by IanPSRocha** [comment]
Task iniciada

**Comment by gustavocarvalho1002** [comment]
Tarefa finalizada!
![160](https://user-images.githubusercontent.com/23438547/60066908-f6db8b00-96de-11e9-8334-03039da1647c.png)
