### ISSUE TITLE
T59 - Desenvolvimento de Teste API - Serviço Player

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#165]
**Descrição**:  
Escrever testes para o serviço de player.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Teste interno de API python.

**Comment by Rdadamos** [comment]
E lá vamos nós

**Comment by gustavocarvalho1002** [comment]
![t59](https://user-images.githubusercontent.com/23438547/60045007-13090900-969a-11e9-8b5a-d25296611980.png)

**Comment by gustavocarvalho1002** [comment]
Testes rodaram! Task concluída por @Rdadamos !
