### ISSUE TITLE
T60 - Desenvolvimento de Teste API - Serviço Evento

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#166]
**Descrição**:  
Escrever testes para o serviço de evento.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Teste interno de API python.

**Comment by Rdadamos** [comment]
Foi

**Comment by gustavocarvalho1002** [comment]
Teste concluído e rodando! 
Tarefa está sendo fechado após conclusão do @Rdadamos !
![t60](https://user-images.githubusercontent.com/23438547/60045070-39c73f80-969a-11e9-8013-8b4a9c361921.png)
