### ISSUE TITLE
T61 - Desenvolvimento de Teste API - Serviço Reward

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#167]
**Descrição**:  
Escrever testes para o serviço de reward.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Teste interno de API python.

**Comment by Rdadamos** [comment]
Vai

**Comment by gustavocarvalho1002** [comment]
@Rdadamos , todos os testes estão rodando! Tarefa já foi dada merge! Estou fechando essa issue e anexando a evidência de sucesso!

**Comment by gustavocarvalho1002** [comment]
![t61](https://user-images.githubusercontent.com/23438547/60045122-6c713800-969a-11e9-8ccd-b8a6dadd6728.png)
