### ISSUE TITLE
T62 - Lista de participantes de evento

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#171]
**Descrição**:  
Mostrar na página de detalhe de eventos uma lista dos players que estão vão participar da atividade.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Mostrar nome do player e foto em miniatura
- [x] Players que selecionarem em "Sair do evento" deverão ter o nome tirado da lista.

**Comment by IanPSRocha** [comment]
Pareamento com @AGoretti vai começar e iremos dar inicio ao desenvolvimento da Feature

**Comment by gustavocarvalho1002** [comment]
Tarefa finalizada já faz mais de 10 dias! Ela não foi corretamente tramitada pelos componentes responsáveis por ela! Deste modo, estou fechando ela e confirmo suas funcionalidade conforme eu testei na branch da devel!
