### ISSUE TITLE
T69 - Adcionar campo "Local" em evento.

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#172]
**Descrição**:  
O evento deverá ter um campo de local para que assim seja possível informar aos player onde o evento vai ocorrer.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Atualizar na API a adição do campo local
- [x] Atualizar a página home com o campo local
- [x] Atualizar a página de detalhe de evento para mostrar o local

**Informações Adcionais**:

NÃO PRECISA ATUALIZAR OS EVENTOS DA LISTA NA PÁGINA "/evento", OUTRA COISA SERÁ FEITA LÁ.

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento da _feature_.

**Comment by murilo-dan** [comment]
PR feito, aguardando review.

**Comment by murilo-dan** [comment]
PR aprovado, fechando _issue_.
