### ISSUE TITLE
T64 - Redirect e Alert em cadastro de reward

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#173]
**Descrição**:  
Colocar um redirect no cadastro de reward para quando for finalizado, redirecionar o usuário para a home e mostrar um alert de sucesso.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Colocar redirect
- [x] Colocar alert

**Comment by djorkaeffalexandre** [comment]
Merjada.
