### ISSUE TITLE
T65 - Validar campos do formulário de cadastro de player

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#176]
**Descrição**:  
O campo que não for preenchido ou preenchido de forma incorreta deverá ser sinalizado.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Mostrar obrigatoriedade do campo usando elementos do bootstrap
- [x] Botão de enviar deverá ficar desabilitado até que o formulário esteja validado

**Comment by djorkaeffalexandre** [comment]
Merjada.
