### ISSUE TITLE
T68 - Revisão de Documentos de Sprint

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2019.1-PretEvent#178]
**Descrição**:  
Revisar os documuntos de Sprint, tanto de sprint review quanto de sprint planning, para verificar se estão todos dentro do template e atualizados .

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Revisão de Sprint Review
- [x] Revisão de Sprint Planning

**Comment by Fealps** [comment]
Terminada revisão da sprint Review

**Comment by gustavocarvalho1002** [comment]
Sprint planning foi feita e revista! Foi verificado que algumas delas estão incompletas! Será feito a correção!
