### ISSUE TITLE
F17 - [FEATURE] Pesquisa de Eventos

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2019.1-PretEvent#179]
**Descrição:**
Disponibilizar na Navbar a opção de poder pesquisar algum evento pelo título do evento.
**Critério de aceitação:**
- [x] Conseguir pesquisar
- [x] Mostrar resultados

**Comment by gustavocarvalho1002** [comment]
Tarefa já foi finalizada há dias! Esqueceram de tramitar essa issue! PR já foi feito tbm conforme indica os dados acima!

**Comment by gustavocarvalho1002** [comment]
Estou fechando essa task!
