### ISSUE TITLE
T74 - Finalizar detalhes para entrega final.

### ISSUE THREAD

**Issue by IanPSRocha** [fga-eps-mds/2019.1-PretEvent#193]
**Descrição**:  
Arrumar os detalhes necessários no site para deixa-lo o mais fluído possível.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] 1. Tecla Enter para Logar.
- [x] 2. Remover Avaliação de Eventos
- [x] 3. Permitir criação de usuário com nome composto
- [x] 4. Atualizar informações de visualização e participação na página de evento
- [x] 5. Remover todos os console.logs
- [x] 6. Formatar alerts para aparecerem na tela
- [x] 7. Substituir campo matrícula por Nome completo.
- [x] 8. Limitar valor de inserção nos campos necessários
- [x] 9. Exibir imagem do player que criou o evento na tela de detalhes do evento
- [x] 10. Localizar dia da semana e mês para português
- [x] 11. Avisar quando o nome de usuário já estiver em uso
- [x] 12. Formatar card da home
- [x] 13. Adicionando alert de participação de evento e redirecionamento
- [x] 14. Corrigir security vulnerabilities no package-lock.json

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento do item 8.

**Comment by murilo-dan** [comment]
Item 8 finalizado.

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento dos itens 2 e 10.

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento dos itens 3 e 7.

**Comment by IanPSRocha** [comment]
Iniciando desenvolvimento dos itens 4, 5 e 9

**Comment by AGoretti** [comment]
Iniciando desenvolvimento do item 1.

**Comment by Fealps** [comment]
Pegando 4 e 9 de onde parou

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento dos itens 3 e 7.

**Comment by murilo-dan** [comment]
Itens 2, 10, 3 e 7 finalizados.

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento do item 12.

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento do item 13.

**Comment by Rdadamos** [comment]
Adicionado task 14

**Comment by Fealps** [comment]
.
.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by IanPSRocha** [comment]
Finalizei o 4 item

**Comment by murilo-dan** [comment]
Finalizado item 13.

**Comment by AGoretti** [comment]
Finalizado item 11

**Comment by Rdadamos** [comment]
Corrigindo security vulnerabilities no package-lock.json
