### ISSUE TITLE
T05 - Criar documento de visão 

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#22]
**Descrição**:  
Escrever o documento de visão(MDS)

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Introdução
- [x] Posicionamento
- [x] Descrição de usuário
- [x] Visão Geral do produto
- [x] Restrições
- [x] Referências

**Comment by IanPSRocha** [comment]
Farei as primeiras modificações apos a adição do template

**Comment by AGoretti** [comment]
Subi o template do documento

**Comment by IanPSRocha** [comment]
Primeiras alterações, como tradução e redução de tópicos foram feitos

**Comment by IanPSRocha** [comment]
Primeiro tópico completo, provável que possua alguns erros ortográficos

**Comment by IanPSRocha** [comment]
1 versão do documento de visão está completa, colocarei pra review, pois talvez precise de correções ortográficas.

**Comment by IanPSRocha** [comment]
Falta descrever qual é a concorrência

**Comment by murilo-dan** [comment]
Feita a formatação do texto, corrigidos alguns erros ortográficos e sumário criado.

**Comment by gustavocarvalho1002** [comment]
Favor preparar a finalização do documento para a apresentação do mesmo na nossa próxima reunião(30/03)

**Comment by gustavocarvalho1002** [comment]
Prezados, atentar ao BUG aberto #50. Se resolvido, favor fechar
