### ISSUE TITLE
T06 - Criar EAP

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#24]
**Descrição**:  
Criar diagrama de EAP do projeto.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Criar diagrama e subir para wiki
- [x] Fazer validação do mesmo.

**Comment by IanPSRocha** [comment]
Primeira versão da EAP feita, talvez nao esteja 100% de acordo com o projeto

**Comment by djorkaeffalexandre** [comment]
A eap foi refeita devido a algumas variações no fluxo do produto, o documento já está no nosso gh-pages e no nosso repositório! Feito isto estou fechando a issue.

Link para a eap: https://github.com/fga-eps-mds/2019.1-PretEvent/blob/master/docs/images/eap_pretevent.png?raw=true
