### ISSUE TITLE
T09 - Criar documento de arquitetura

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#25]
**Descrição**:  
Criar o documento de arquitetura para descrever a estrutura do sistema e sua visão.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Introdução
- [x] Representação da arquitetura a ser utilizada.
- [x] Metas e restrições
- [x] Visão lógica(visão geral, visão de pacotes)
- [x] Visão de processos
- [ ] Visão de dados

**Informações Adcionais:**
Os passos descritos acima poderão ser alterados conforme a necessidade, visto que mais itens poderão ser adcionados.

**Comment by RochaCarla** [comment]
Cadê o issue template? não tem descrição da issue, nem tarefas, nem criterio de aceitação, nem assignees...  :(

**Comment by gustavocarvalho1002** [comment]
@RochaCarla as issues foram atualizadas com suas devidas templates

**Comment by gustavocarvalho1002** [comment]
Template base já está no repositório

**Comment by gustavocarvalho1002** [comment]
Documento está parcialmente pronto. Mais informações serão adicionadas em uma futura atualização
