### ISSUE TITLE
T15 - Configurar Docker no ambiente de desenvolvimento 

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#26]
Descrição:
Configurar o Docker no ambiente de desenvolvimento.

Atividade(s) a ser(em) realizada(s):
- [x] Docker Back
- [ ] Docker Front

**Comment by andrebargas** [comment]
Ambiente de dev dockerisado criado para servico de players com db funfando 100%

**Comment by gustavocarvalho1002** [comment]
Ambiente de desenvolvimento com o docker está pronto!
