### ISSUE TITLE
T12 - Configurar CodeClimate 

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#27]
**Descrição**:  
Configurar no repositório do projeto o CodeClimate para vizualização de dados da "saúde" do código.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Estudar CodeClimate
- [x] Botar CodeClimate para funcionar

**Comment by Rdadamos** [comment]
Ainda não foi feito.

**Comment by Rdadamos** [comment]
Feito com configurações default.
