### ISSUE TITLE
S01 - Treinamentos de MDS

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#3]
- [x] Git
- [x] Django
- [ ] Angular

**Comment by IanPSRocha** [comment]
Vou participar

**Comment by djorkaeffalexandre** [comment]
Treinamento de GIT marcado para 20.03.2019 as 20:30h via hangouts.
Por: @gustavocarvalho1002 

@IanPSRocha @b2198 @murilo-dan @Fealps @AGoretti

**Comment by b2198** [comment]
Vou participar

**Comment by murilo-dan** [comment]
Vou participar

**Comment by andrebargas** [comment]
Olá, durante o treinamento de Django irei ensinar um pouco de Flask também. Caso queiram ir adiantando, segue alguns links para estudo : 
* https://tutorial.djangogirls.org/pt/
* https://www.djangoproject.com/start/
* http://flask.pocoo.org/docs/1.0/quickstart/

**Comment by gustavocarvalho1002** [comment]
MDS já tem um conhecimento minimo para conseguir mexer na API em Django. 
Agora é necessário fazer uma ambientação em Angular. Será marcado uma data para tal.
