### ISSUE TITLE
F01 - [FEATURE] - Criação do serviço "player"

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#43]
**Descrição:**
Criar serviço de player com operações de CRUD funcionais. 

**Critério de aceitação:**
É necessário ter as seguintes operações REST: 
- [x] Create(Enviar arquivo json e ele ficar persistido no banco)
- [x] Read(Recuperar um json da api)
- [x] Update (Atualizar dados de uma registro já existente)
- [x] Delete ( Deletar um registro no meu banco)

**Comment by IanPSRocha** [comment]
Basicamente todo processo ja foi elaborado no grosso, falta refinar algumas partes antes de pedir Pull Request

**Comment by IanPSRocha** [comment]
Pequenas modificações necessarias ao CRUD foram feitas

**Comment by IanPSRocha** [comment]
Aparentemente está funcional

**Comment by IanPSRocha** [comment]
Possuindo bastante dificuldade com o manuseio de url's, mas fazendo progresso

**Comment by IanPSRocha** [comment]
100% concluido

**Comment by djorkaeffalexandre** [comment]
Feito. LGFM.
