### ISSUE TITLE
[BUG] - Sumário do Documento de Visão funcionando incorretamente 

### ISSUE THREAD

**Issue by andrebargas** [fga-eps-mds/2019.1-PretEvent#50]
Sumário no documento de visão do git.io não esta linkando para os sub tópicos do documento.

**Passos para reprodução:**
1. Vá até https://fga-eps-mds.github.io/2019.1-PretEvent/#/vision_doc?id=sub2
2. Clique no sumário

**Comportamento esperado:**
Deveria linkar para o sub tópicos

**Comment by gustavocarvalho1002** [comment]
Prezado, erro é no documento de visão
