### ISSUE TITLE
T18 - Criar protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by andrebargas** [fga-eps-mds/2019.1-PretEvent#54]
**Descrição**:  
Criar protótipo de baixa fidelidade

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Deve ser intuitivo
- [x] Deve representar o visual da aplicação

**Informações Adcionais**:
Será o template do Prototipo de alta fidelidade

**Comment by djorkaeffalexandre** [comment]
Fechada
