### ISSUE TITLE
T01 - Configurar o Zenhub

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#6]
**Descrição**
Configurar o zenhub no repositório e setar as milestones e épicos.

**Tarefas**
- [x] Configurar o zenhub
- [x] Criar os épicos no zenhub
- [x] Crias os milestones no zenhub

**Comment by gustavocarvalho1002** [comment]
Zenhub está funcional!

**Comment by gustavocarvalho1002** [comment]
US estão sem milestones no Zenhub. Os mesmos serão definidos na próxima reunião do sábado(30/03)
