### ISSUE TITLE
F05 - [FEATURE] - Criação do serviço "event"

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#60]
**Descrição:**
Criar serviço de event com operações de CRUD funcionais. 

**Critério de aceitação:**
É necessário ter as seguintes operações REST: 
- [x] End point para criação de evento
- [x] End point para editar de evento
- [x] End point para deletar de evento
- [x] End point para recuperar de evento(por id)
- [x] End point para recuperar de eventos

**Comment by murilo-dan** [comment]
Trabalhando no CRUD do evento.

**Comment by IanPSRocha** [comment]
Pareando com Murilo para ajustar finalização do CRUD

**Comment by murilo-dan** [comment]
CRUD dos eventos funcionando normalmente, aguardando review.

**Comment by djorkaeffalexandre** [comment]
Merjado
