### ISSUE TITLE
F06 - [FEATURE] - Página de lista eventos

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#61]
**Descrição:**
Criação de página no app que mostre todos os eventos que estão agendados para acontecer

**Critério de aceitação:**
- [x] Eventos que já aconteceram não deverão aparecer na lista
- [x] Eventos deverão aparecer por ordem de data crescente
- [x] Na lista, deverá aparecer somente o nome do evento, e sua data.

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento da _feature_, sob orientação do @djorkaeffalexandre.

**Comment by murilo-dan** [comment]
Os eventos já aparecem no fronte em ordem crescente de data.
O título do evento está linkando para a página de detalhes do evento.

**Comment by murilo-dan** [comment]
Tela de eventos com alguns eventos teste, ordenados por data.

![Captura de tela de 2019-05-27 23-03-40](https://user-images.githubusercontent.com/48605413/58445658-d7e3dc00-80d3-11e9-99b6-4b2fbd779d34.png)

**Comment by murilo-dan** [comment]
PR feito, aguardando _review_.
