### ISSUE TITLE
F07 - [FEATURE] - Formulário de evento

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#62]
**Descrição:**
Deverá ser criado um formulário para cadastro de evento com o seguintes campos:
* Nome
* Descrição
* Local
* Data
* Hora
* Vagas
No registro de evento no banco, deverá ter o id do player que criou o evento, pois somente ele será autorizado a realizar operações CRUD sobre o registro do evento. 

**Critério de aceitação:**
- [x] Validação dos campos
- [x] Não será permitido criação de eventos anteriores a data atual do dia cadastro do evento

**Comment by IanPSRocha** [comment]
Após dar uma estudada em angular, iniciarei o desenvolvimento da Feature

**Comment by IanPSRocha** [comment]
Pareando com @AGoretti para desenvolvimento

**Comment by IanPSRocha** [comment]
![Captura de tela de 2019-04-29 21-31-51](https://user-images.githubusercontent.com/42422835/56935263-4417f380-6ac6-11e9-98e6-ff55ff3cc165.png)
