### ISSUE TITLE
F08 - [FEATURE] - Página de visualização de evento

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#63]
**Descrição:**
O app deverá ter uma página para mostrar os detalhes de um evento, mostrando todos os seus atributos, inclusive o nome do criador daquele evento. 

**Critério de aceitação:**
- [ ] Mostrar todos os dados do evento, com formatação.
- [ ] Mostrar o nome do criador do evento.
- [ ] Testes

**Comment by Fealps** [comment]
Crud Inicializado

**Comment by Fealps** [comment]
Pareando com o @AGoretti para entender melhor sobre autenticação de token e como recuperar o user id via token

**Comment by gustavocarvalho1002** [comment]
Dívida para a Sprint 6

**Comment by AGoretti** [comment]
Pareando com o @Fealps, estamos com problemas em requisitar o id do evento para utilizar de parameto na rota.

**Comment by AGoretti** [comment]
Faltando somente arrumar o botao da modal do full image.
