### ISSUE TITLE
F09 - [FEATURE] - Inscrição de player em evento

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#64]
**Descrição:**
Desenvolver solução para que seja possível um player se inscrever em um evento, através de um botão participar. O registro do evento deverá guardar o id de todos os usuários que confirmaram participação. 
O botão participar deve estar disponível na lista de eventos(#61 ), ao lado de cada um deles na lista, como também na página de visualização dos dados do evento(#63 ).

**Critério de aceitação:**
- [x] Assim que o usuário confirmar participação, onde antes nos botões de lia "Participar", deve estar "Cancelar Participação"
- [x] O registro de evento deverá guardar o id de cada usuário que estiver participando do evento
- [x] O botão participar não deverá estar disponível para o criador do evento.

**Comment by IanPSRocha** [comment]
Backend da feature já foi modificado pelo @AGoretti, agora iremos parear para trabalhar no Front

**Comment by IanPSRocha** [comment]
Pareando com @AGoretti para resolução do front

**Comment by IanPSRocha** [comment]
Na tentativa de retornar o ID do player junto com o token, estamos enfrentando esse erro

![Captura de tela de 2019-06-03 21-47-34](https://user-images.githubusercontent.com/42422835/58843521-34ea0f80-8649-11e9-94b4-9bf236f96517.png)

**Comment by gustavocarvalho1002** [comment]
Observado! @andrebargas atuara para resolver o problema

**Comment by AGoretti** [comment]
![Captura de tela de 2019-06-05 18-28-06](https://user-images.githubusercontent.com/40605515/58998850-46fab800-87d9-11e9-906d-aff5bc84fea2.png)
Feature funcionando, faltando somente corrigir esse error.
