### ISSUE TITLE
F10 - [FEATURE] - Lista de participantes de um evento

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#65]
**Descrição:**
Cada evento deverá ter uma lista de participantes do evento, mostrando nome e foto.  

**Critério de aceitação:**
- [x] A lista deverá conter todos os participantes daquele evento

**Comment by IanPSRocha** [comment]
eu e @AGoretti iniciaremos o desenvolvimento da Feature pareando.

**Comment by IanPSRocha** [comment]
Aproveitamos para corrigir um erro, na qual o id continuava armazenado no localstorage. Foi arrumado

**Comment by AGoretti** [comment]
Corrigimos a linkagem na navbar para rankings.

**Comment by IanPSRocha** [comment]
Feature foi analisada pelo @gustavocarvalho1002 e já foi aprovada e na development
