### ISSUE TITLE
F11 - [FEATURE] - Criação do serviço "reward"

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#66]
**Descrição:**
Criar serviço de reward com operações de CRUD funcionais. 

**Critério de aceitação:**
É necessário ter as seguintes operações REST: 
- [x] Create(Enviar arquivo json e ele ficar persistido no banco)
- [x] Read(Recuperar um json da api)

**Comment by murilo-dan** [comment]
Pareando com @IanPSRocha para iniciar o desenvolvimento da feature.

**Comment by IanPSRocha** [comment]
Finalizamos os requisitos dessa issue

**Comment by IanPSRocha** [comment]
Finalizado os criterios de aceitação e testados

**Comment by IanPSRocha** [comment]
Segue em anexo, uma captura de tela mostrando o json retornado da api rewards

![Captura de tela de 2019-04-18 10-18-11](https://user-images.githubusercontent.com/42422835/56363846-7b7fc980-61c3-11e9-8161-653c97ecf4d5.png)
