### ISSUE TITLE
F12 - [FEATURE] - Cadastro de reward

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#67]
**Descrição:**
Deverá ser possível cadastrar um prêmio durante a criação de um evento. O mesmo deverá conter os seguintes campos:
* Pontos
* Descrição

**Critério de aceitação:**
- [x] O campo de pontos deverá aceitar somente números, e um valor maior que 0.

**Comment by murilo-dan** [comment]
Pareando com @Fealps , sob orientação do @djorkaeffalexandre , para iniciar o desenvolvimento.

**Comment by murilo-dan** [comment]
Criação da feature finalizada, aguardando review.

**Comment by murilo-dan** [comment]
Tela para o cadastro de reward.

![reward](https://user-images.githubusercontent.com/48605413/56998190-c7961b00-6b80-11e9-9b63-1d7bd9eaf691.png)
