### ISSUE TITLE
F13 - [FEATURE] - Página de visualização de reward

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#68]
**Descrição:**
O app deverá ter uma página para mostrar os detalhes de um reward, mostrando todos os seus atributos.

**Critério de aceitação:**
- [x] Mostrar todos os dados de reward
# DEFINIR CRITÉRIOS

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento da _feature_.

**Comment by murilo-dan** [comment]
Endpoint de visualização de recompensa.

![Captura de tela de 2019-05-11 03-09-25](https://user-images.githubusercontent.com/48605413/57565820-b5935400-739a-11e9-96bf-3b8c5c506be1.png)

**Comment by murilo-dan** [comment]
Dados da recompensa selecionada apresentados.

![Captura de tela de 2019-05-11 16-47-49](https://user-images.githubusercontent.com/48605413/57574286-91705b00-740c-11e9-8c7e-113b99b94dcf.png)

**Comment by murilo-dan** [comment]
_Feature_ finalizada, aguardando review.

**Comment by gustavocarvalho1002** [comment]
Feature feita e aceita!
