### ISSUE TITLE
F14 - [FEATURE] - Ranking de players

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#69]
**Descrição:**
Criar página com ranking de players por ordem decrescente de pontos

**Critério de aceitação:**
- [x] Ordem deverá ser em ordem decrescente por pontos
- [x] Na lista, deverá aparecer somente pontos e nome do player

**Comment by djorkaeffalexandre** [comment]
Valeu man!

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento da _feature_.

**Comment by murilo-dan** [comment]
Tela de ranking apresentando os dados requisitados (nome e pontos) com adição do campo de avatar do jogador.

![Captura de tela de 2019-05-20 23-59-29](https://user-images.githubusercontent.com/48605413/58065219-5f24d300-7b5b-11e9-95ba-b66190fb1314.png)

**Comment by murilo-dan** [comment]
Observação: os dados retornados do _backend_ já são ordenados por ordem decrescente de pontos, de forma que não foi necessário programar essa funcionalidade no _frontend_.

**Comment by murilo-dan** [comment]
Desenvolvimento da _feature_ finalizada, aguardando _review_ do PR.

**Comment by gustavocarvalho1002** [comment]
PR desta tarefa já foi aceito! Fecharei essa issue
