### ISSUE TITLE
T04 - Criar planilha de horários e conhecimento

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#7]
**Descrição**
Criação de planilha de horários para organizar reuniões e de conhecimento para momentos de pair programming.

**Tarefas**
- [x] Criar planilha de horários
- [x] Criar planilha de conhecimento

**Comment by gustavocarvalho1002** [comment]
As mesmas foram criadas e se encontram no Drive da equipe. 

Link: https://docs.google.com/spreadsheets/d/1rhC4VpY0Z1Tx_cNNM92I3RbHend7R_pXyT88R9c55G4/edit?usp=sharing
