### ISSUE TITLE
F15 - [FEATURE] - Página home

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#70]
**Descrição:**
O aplicativo deverá ter uma página inicial, onde a mesma será a primeira a aparecer assim que acessar o aplicativo. 

**Critério de aceitação:**
- [x] Html deve ser responsivo
- [x] Deve respeitar especificações do protótipo de alta fidelidade

**Comment by AGoretti** [comment]
Feita a tool bar usando material

**Comment by gustavocarvalho1002** [comment]
Prezado, favor ficar atento as tarefas da atividade. A mesma não inclui toolbar

**Comment by AGoretti** [comment]
A Pagina home esta com carousel e com principais eventos e noticias seguida da lista dos eventos
