### ISSUE TITLE
F16 - [FEATURE] - Navbar

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#71]
**Descrição:**
Desenvolver elementos de navegação sidebar e navbar.

**Critério de aceitação:**
- [x] Deverá seguir padrão do protótipo de alta fidelidade

**Comment by AGoretti** [comment]
![Captura de tela de 2019-04-27 09-24-12](https://user-images.githubusercontent.com/40605515/56851646-c26a6f00-68e7-11e9-8d09-ae4e560d3447.png)

Finalizado Conforme a imagem
