### ISSUE TITLE
T25 - Criação de folha de estilo

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#86]
**Descrição**:  
Criação das folhas de estilo de código do frontend e backend.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] folha de estilo typescript
- [x] folha de estilo python

**Comment by gustavocarvalho1002** [comment]
Tarefa está sendo iniciada agora.

**Comment by gustavocarvalho1002** [comment]
Folhas criadas
