### ISSUE TITLE
F17 - Autenticação de Usuário

### ISSUE THREAD

**Issue by Rdadamos** [fga-eps-mds/2019.1-PretEvent#87]
**Descrição:**
Permitir que o usuário autentique-se no sistema.

**Critério de aceitação:**
- [x] Criar campo de senha no player
- [x] Criação do token de usuário
- [x] Criptografia de senha
- [x] Endpoint de login

**Comment by murilo-dan** [comment]
Iniciando desenvolvimento da feature.

**Comment by IanPSRocha** [comment]
Irei parear com @murilo-dan para o desenvolvimento

**Comment by IanPSRocha** [comment]
@murilo-dan Fez as ultimas modificações necessárias para o pleno funcionamento

**Comment by murilo-dan** [comment]
Segue tela do token de usuário sendo retornado com sucesso. 
Aguardando review.
![login_endpoint_token](https://user-images.githubusercontent.com/48605413/56462243-542d2600-6396-11e9-9172-f6aaabf0ca0a.png)
