### ISSUE TITLE
T27 - Diagrama de casos de uso

### ISSUE THREAD

**Issue by djorkaeffalexandre** [fga-eps-mds/2019.1-PretEvent#91]
**Descrição**:  
Criar o diagrama de caso de uso do sistema.

**Atividade(s) a ser(em) realizada(s)**: 
- [ ] Criar o documento de caso de uso em integração com EPS & MDS.
- [ ] Colocar o documento no gh-pages do repositório.

**Comment by IanPSRocha** [comment]
Iniciarei os estudos para desenvolver o diagrama

**Comment by Fealps** [comment]
Diagrama feito usando Lucid Chart.
