### ISSUE TITLE
T28 - Criação de footer 

### ISSUE THREAD

**Issue by gustavocarvalho1002** [fga-eps-mds/2019.1-PretEvent#92]
**Descrição**:  
Criar footer para a página do app. O mesmo vai servir para conter informações básicas do projeto, como contato, ajuda, etc.

**Atividade(s) a ser(em) realizada(s)**: 
- [x] Criar footer com posição fixa no final da página
- [x] Deve obedecer os padrões de cores do protótipo

**Comment by b2198** [comment]
Tarefa finalizada.
